[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$major.$minor.$patch$prerelease"
version = "0.9.0"
version_files = [
    "package.json:version",
    "cap_config.yml",
    ".cz.toml"
]
