[default.extend-words]
# French words that are valid
cours = "cours"
appareil = "appareil"

# Words valid in multiple languages
periode = "periode"

# Indonesian words that are valid
bundel = "bundel"
